plugins {
    id 'com.android.application'
}

android {

    def keyProps = new Properties()
    def keyPropsFile = rootProject.file('secret')

    namespace = 'com.data_dive.com.clipster'
    compileSdk = 37

    signingConfigs {
        // load from secret file for not sharing on git

        if (keyPropsFile.exists()) {
            keyPropsFile.withInputStream { keyProps.load(it) }

            clipster_key {
                keyAlias = keyProps['keyAlias']
                keyPassword = keyProps['keyPassword']
                storeFile = file(keyProps['storeFile'])
                storePassword = keyProps['storePassword']
            }
        }

    }

    defaultConfig {
        applicationId = "com.data_dive.com.clipster"
        minSdk = 26
        targetSdk = 36
        versionCode = 8
        versionName = "0.5.0"
    }

    buildTypes {
        release {
            minifyEnabled = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            if (keyPropsFile.exists()) {
                signingConfig = signingConfigs.clipster_key
            }
        }
    }

    // Needed for fernet-java8, otherwise strange untrackable behaviour
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.core:core:1.19.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'
    implementation 'com.macasaet.fernet:fernet-java8:1.5.0'
    implementation 'com.amdelamar:jhash:2.2.0'
}
